### ISSUE TITLE
Unable to read from a queue with arguments set

### ISSUE THREAD

**Issue by frankyin1019** [Stratio/Spark-RabbitMQ#18]
Hi. 

It seem the Stream can not read from a queue with x-max-length set.

The error I'm getting is :
```
ERROR ReceiverTracker: Deregistered receiver for stream 0: Restarting receiver with delay 2000ms: Trying to connect again
```

If I do not set the x-max-length of the queue. Everything works well.

Actually we tried to set "x-message-ttl", and the same error occurs.

Everything works when we do not set any arguments when creating the (durable) queue.

**Comment by karimEssawi** [comment]
Hi,

I'm having a similar problem as I'm trying to connect to an existing queue with 'x-message-ttl' being set, but I get:
```
channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'spark_event_queue' in vhost '/': received none but current is the value '300000' of type 'long', class-id=50, method-id=10)
```

**Comment by Gschiavon** [comment]
Hi! this is solved in #26 .
Thank you.

**Comment by yenki** [comment]
I think this problem is back in 3.0, at least when using any rabbitmq argument that is not a string. See my comment [here](https://github.com/Stratio/Spark-RabbitMQ/commit/f50ced494ec30965a8eb6a86a91b5e2b22207c47)

**Comment by croofec** [comment]
On version 0.4.0-SNAPSHOT with params.put("x-message-ttl", "30000");

`Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'in.all' in vhost '/': received '30000' but current is '30000', class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:226)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
	... 21 more`
