### ISSUE TITLE
Possibilty to adapt the Scala code to add the rabbitmq port number ?

### ISSUE THREAD

**Issue by enahwe** [Stratio/spark-rabbitmq#45]
Hi guys, where is it possible to modify the Scala code to specify the rabbitmq port number when it's different as the default value ?
For information if I add the port number property in the Scala code into the params list, this has no effect at all.
Thank's.

**Comment by compae** [comment]
Hi,

I think that in the master version this issue is solved. You can use the property "hosts" in the Map of options.

Thanks.

**Comment by bc-santhosh** [comment]
@compae I still face the port number issue and I don't see anywhere the portNumber set in the code base(Possibly in Consumer.scala). Also, setting the "hosts" property tries to connect to localhost(default host). May I know if I miss something? 

Thanks

**Comment by compae** [comment]
Hi @bc-santhosh you can set the port in the hosts property. One example:

hosts = host1:12345, host2:12345, host3:12345

The code in amqp library that execute this code is:

`public static Address parseAddress(String addressString) {
        int idx = addressString.indexOf(':');
        return (idx == -1) ?
            new Address(addressString) :
            new Address(addressString.substring(0, idx),
                        Integer.parseInt(addressString.substring(idx+1)));
    }`
